echo 'Starting Command Node'
ssh command.re2.detmacro 'cd CRARiskExperiment2/; sh StartCommand.sh'

echo 'Starting Database Servers'
ssh db0.re2.detmacro 'cd CRARiskExperiment2/; sh DBStart.sh'
ssh db1.re2.detmacro 'cd CRARiskExperiment2/; sh DBStart.sh'
ssh db2.re2.detmacro 'cd CRARiskExperiment2/; sh DBStart.sh'
ssh db3.re2.detmacro 'cd CRARiskExperiment2/; sh DBStart.sh'

echo 'Starting Control Nodes'
ssh c0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh client'
ssh c1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh client'
ssh c2.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh client'
ssh isp0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh isp1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh bgp0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh bgp1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh router0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh router1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh bc.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh bc'
ssh auth0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh auth 0'
ssh auth1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh auth 1'
ssh auth2.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh auth 2'
ssh auth3.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh auth 3'
ssh db0.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh db1.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh db2.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh db3.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh nothing'
ssh attacker.re2.detmacro 'cd CRARiskExperiment2/; sh StartControl.sh attacker'