ssh attacker.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh auth0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh auth1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh auth2.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh auth3.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh bc.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh bgp0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh bgp1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh c0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh c1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh c2.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh command.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh db0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh db1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh db2.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh db3.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh isp0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh isp1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh router0.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh
ssh router1.re2.detmacro 'sh' < CRARiskExperiment2/InstallScreen.sh